// frontend/components/TokSlider/TokSlider.vue
<template>
  <div
    class="w-full h-screen p-6 transition-all duration-300 ease-in-out"
    id="container"
  >
    <swiper
      class="h-full max-w-[520px] min-w-[425px] rounded-xl p-6 transition-all duration-300 ease-in-out"
      :direction="'vertical'"
      :modules="modules"
      :slides-per-view="1"
      :space-between="25"
      :mousewheel="true"
      :keyboard="true"
      @swiper="setSwiper"
      @slide-change="handleSlideChange"
    >
      <swiper-slide v-if="isLoading">
        <div class="w-full h-full flex justify-center items-center">
          Loading...
        </div>
      </swiper-slide>

      <template v-else>
        <swiper-slide
          v-for="(book, i) in books"
          :key="book.cover_i"
          class="p-3.5"
        >
          <div
            class="h-[95%] rounded-xl"
            v-if="book.cover_i || books.length === 0"
            :id="`book_slide_${i}`"
          >
            <NuxtImg
              class="w-full h-full rounded-xl object-contain transition-all duration-300 ease-in-out"
              :src="`https://covers.openlibrary.org/b/id/${book.cover_i}-L.jpg`"
              :preload="true"
              :placeholder="
                img(
                  `https://covers.openlibrary.org/b/id/${book.cover_i}-L.jpg`,
                  { h: 10, f: 'png', blur: 2, q: 50 }
                )
              "
              @load="imgLoadHandler"
            />
            <div v-if="book.title" class="text-center">
              {{ book.title }}
            </div>
          </div>
          <div v-else :id="`book_slide_${i}`">
            <NuxtImg
              class="object-contain w-full"
              src="https://placehold.co/490x670/trasnparent/white"
            />
            <div v-if="book.title" class="text-center">
              {{ book.title }}
            </div>
          </div>
        </swiper-slide>
      </template>
    </swiper>

    <div @click="shake">shake</div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";
import { Swiper as SwiperClass } from "swiper";
import { Swiper, SwiperSlide } from "swiper/vue";
import { Keyboard, Mousewheel } from "swiper/modules";
import type { Book } from "~/types/books.types";

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import { gsap } from "gsap";
import { Draggable } from "gsap/Draggable";
import { createDraggable } from "./utils/createDraggable";
import { shakeSlide } from "./utils/shakeSlide";

const props = defineProps({
  books: {
    type: Array as () => Book[],
    required: true,
  },
  isLoading: {
    type: Boolean,
    required: true,
  },
  fetchNextPage: {
    type: Function,
    required: true,
  },
  onSlideChange: {
    type: Function,
    default: undefined,
  },
});

const img = useImage();

onMounted(() => {
  gsap.registerPlugin(Draggable);
});

const modules = [Keyboard, Mousewheel];

const swiperInstance = ref<SwiperClass>({} as SwiperClass);
const activeIndex = ref(0);
const firstImgIsLoaded = ref(false);
console.log({ firstImgIsLoaded });

const setSwiper = (swiper: SwiperClass) => {
  swiperInstance.value = swiper;
};

const handleSlideChange = (swiper: SwiperClass) => {
  activeIndex.value = swiper.activeIndex;
  createDraggable(swiper.activeIndex, swiper);

  props.onSlideChange?.(swiper.activeIndex);
};

const imgLoadHandler = () => {
  setTimeout(() => {
    firstImgIsLoaded.value = true;
  }, 600);
};

const shake = () => {
  if (swiperInstance.value.activeIndex === 0) {
    shakeSlide(swiperInstance.value.slides[activeIndex.value]);
  }
};

watch(activeIndex, (newVal) => {
  if (
    swiperInstance.value &&
    props.books.length > 0 &&
    newVal === props.books.length - 2
  ) {
    props.fetchNextPage();
  }
});

watch(props.books, (newVal) => {
  if (newVal.length > 0) {
    nextTick(() => {
      createDraggable(activeIndex.value, swiperInstance.value);
    });
  }
});

watch(firstImgIsLoaded, (newVal) => {
  if (newVal) {
    nextTick(() => {
      shake();
    });
  }
});
</script>

// frontend/src/widgets/TokSlider/TokSlider.tsx
import {FC, useEffect, useState} from 'react';
import styled from 'styled-components';
import {Keyboard, Mousewheel} from 'swiper/modules';
import {Swiper, SwiperClass, SwiperSlide} from 'swiper/react';

//@ts-ignore
import 'swiper/css';

import {Book} from '~/entities';
import {changeTheme, colors} from '~/shared/theme';

import {generateRandomHexColor} from './utils';

const Wrapper = styled.div<{themeColor: typeof colors}>`
  width: 100%;
  height: 100vh;
  background-color: ${({themeColor}) => themeColor.bg};
  padding: 25px;
  transition: all 0.3s ease-in-out;
`;

const StyledSwiper = styled(Swiper)<{themeColor: typeof colors}>`
  height: 100%;
  max-width: 520px;
  min-width: 425px;
  background-color: ${({themeColor}) => themeColor.primary};
  border-radius: 20px;
  padding: 25px;
  transition: all 0.3s ease-in-out;
`;

const StyledSwiperSlide = styled(SwiperSlide)`
  width: 100%;
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: transparent;
  border-radius: 10px;
  margin: 0 auto;

  img {
    border-radius: 20px;
  }
`;

type TokSliderProps = {
  books: Book[];
  isLoading: boolean;
  fetchNextPage: () => void;
  onSlideChange?: (index: number) => void;
};

export const TokSlider: FC<TokSliderProps> = ({
  books,
  isLoading,
  fetchNextPage,
  onSlideChange,
}) => {
  const [swiper, setSwiper] = useState<SwiperClass | null>(null);
  const [activeIndex, setActiveIndex] = useState(0);

  useEffect(() => {
    if (swiper && books.length > 0 && activeIndex === books.length - 2) {
      fetchNextPage();
    }
  }, [activeIndex, books.length, fetchNextPage, swiper]);

  useEffect(() => {
    swiper?.update();
  }, [books]);

  return (
    <Wrapper themeColor={colors}>
      <StyledSwiper
        spaceBetween={25}
        slidesPerView={1}
        lazyPreloadPrevNext={3}
        direction="vertical"
        onSwiper={(swiper) => setSwiper(swiper)}
        onSlideChange={(swiper) => {
          setActiveIndex(swiper.activeIndex);

          if (onSlideChange) {
            onSlideChange(swiper.activeIndex);
            changeTheme({
              secondary: generateRandomHexColor(),
              primary: generateRandomHexColor(),
              bg: generateRandomHexColor(),
            });
          }
        }}
        mousewheel
        keyboard
        modules={[Keyboard, Mousewheel]}
        themeColor={colors}
      >
        {isLoading && <StyledSwiperSlide>Loading...</StyledSwiperSlide>}
        {!isLoading &&
          books.map((book) => (
            <StyledSwiperSlide key={book.cover_i}>
              <img
                loading="lazy"
                height={'100%'}
                width={'100%'}
                src={`https://covers.openlibrary.org/b/id/${book.cover_i}-L.jpg`}
                style={{objectFit: 'contain', borderRadius: '20px'}}
              />
            </StyledSwiperSlide>
          ))}
      </StyledSwiper>
    </Wrapper>
  );
};
